// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:budget_app/data/models/budget.dart';
import 'package:budget_app/data/models/category.dart';
import 'package:budget_app/data/models/recurring_transaction.dart';
import 'package:budget_app/data/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(TransactionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(TransactionAdapter());
  }
}
