import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'app.dart';
import 'core/constants/hive_boxes.dart';
import 'data/models/budget.dart';
import 'data/models/category.dart';
import 'data/models/transaction.dart';
import 'data/repositories/transaction_repository.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must be called before any DateFormat with a non-English locale is used.
  await initializeDateFormatting('sv_SE');

  await _initHive();

  runApp(
    // ProviderScope is the Riverpod root — must wrap the entire app.
    // All providers are created and cached inside this scope.
    const ProviderScope(
      child: BudgetApp(),
    ),
  );
}

Future<void> _initHive() async {
  // Initialises Hive and sets the storage path via path_provider.
  await Hive.initFlutter();

  // Register the TypeAdapters generated by build_runner.
  // Order doesn't matter, but typeIds must be unique (0, 1, 2).
  Hive.registerAdapter(CategoryAdapter()); // typeId: 0
  Hive.registerAdapter(TransactionAdapter()); // typeId: 1
  Hive.registerAdapter(BudgetAdapter()); // typeId: 2

  // Open all boxes upfront so repositories can access them
  // synchronously via Hive.box<T>() anywhere in the app.
  await Future.wait([
    Hive.openBox<Category>(HiveBoxes.categories),
    Hive.openBox<Transaction>(HiveBoxes.transactions),
    Hive.openBox<Budget>(HiveBoxes.budgets),
    Hive.openBox(HiveBoxes.settings), // non-typed — stores primitives
  ]);

  // Seed the default Swedish categories on first launch.
  // Safe to call every time — skips if already seeded.
  await TransactionRepository().seedDefaultCategories();
}
