import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'app.dart';
import 'core/constants/hive_boxes.dart';
import 'data/models/budget.dart';
import 'data/models/category.dart';
import 'data/models/recurring_transaction.dart';
import 'data/models/transaction.dart';
import 'data/repositories/recurring_transaction_repository.dart';
import 'data/repositories/transaction_repository.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must be called before any DateFormat with a non-English locale is used.
  await initializeDateFormatting('sv_SE');

  await _initHive();

  runApp(
    const ProviderScope(
      child: BudgetApp(),
    ),
  );
}

Future<void> _initHive() async {
  await Hive.initFlutter();

  // Register all TypeAdapters (generated by build_runner)
  Hive.registerAdapter(CategoryAdapter()); // typeId: 0
  Hive.registerAdapter(TransactionAdapter()); // typeId: 1
  Hive.registerAdapter(BudgetAdapter()); // typeId: 2
  Hive.registerAdapter(RecurringTransactionAdapter()); // typeId: 3

  // Open all boxes in parallel
  await Future.wait([
    Hive.openBox<Category>(HiveBoxes.categories),
    Hive.openBox<Transaction>(HiveBoxes.transactions),
    Hive.openBox<Budget>(HiveBoxes.budgets),
    Hive.openBox<RecurringTransaction>(HiveBoxes.recurringTransactions),
    Hive.openBox(HiveBoxes.settings),
  ]);

  // Seed default Swedish categories on first launch
  await TransactionRepository().seedDefaultCategories();

  // Auto-generate recurring transactions for the current month
  await RecurringTransactionRepository().generateForCurrentMonth();
}
